[package]
name = "cli_helpers"
version = "0.1.0"
authors = ["Joakim FrostegÃ¥rd <joakim.frostegard@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
gumdrop = "0.7"
serde = { version = "1", features = ["derive"] }
toml = "0.5"